/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package questionario;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Tech Consertos
 */
public class Questionario extends javax.swing.JFrame {

    /**
     * Creates new form Questionario
     */
    public Questionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPergunta1 = new javax.swing.ButtonGroup();
        bgPergunta2 = new javax.swing.ButtonGroup();
        bgPergunta3 = new javax.swing.ButtonGroup();
        jlPergunta1 = new javax.swing.JLabel();
        jrbSoftware = new javax.swing.JRadioButton();
        jrbHardware = new javax.swing.JRadioButton();
        jrbPerifericos = new javax.swing.JRadioButton();
        jrbModem = new javax.swing.JRadioButton();
        jlPergunta2 = new javax.swing.JLabel();
        jrbBit = new javax.swing.JRadioButton();
        jrbByte = new javax.swing.JRadioButton();
        jrbMicrobyte = new javax.swing.JRadioButton();
        jrbMinibite = new javax.swing.JRadioButton();
        jlPergunta3 = new javax.swing.JLabel();
        jrb1000quilobytes = new javax.swing.JRadioButton();
        jrb10Bits = new javax.swing.JRadioButton();
        jrb1000Megabytes = new javax.swing.JRadioButton();
        jrb10000bytes = new javax.swing.JRadioButton();
        jbSubmeter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlPergunta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlPergunta1.setText("1: O termo técnico para designar a parte fisica do computador é:*");

        bgPergunta1.add(jrbSoftware);
        jrbSoftware.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbSoftware.setText("Software");

        bgPergunta1.add(jrbHardware);
        jrbHardware.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbHardware.setText("Hardware");

        bgPergunta1.add(jrbPerifericos);
        jrbPerifericos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbPerifericos.setText("Periféricos");

        bgPergunta1.add(jrbModem);
        jrbModem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbModem.setText("Modem");

        jlPergunta2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlPergunta2.setText("2: A menor quantidade de informação binaria chama-se:*");

        bgPergunta2.add(jrbBit);
        jrbBit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbBit.setText("Bit");
        jrbBit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBitActionPerformed(evt);
            }
        });

        bgPergunta2.add(jrbByte);
        jrbByte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbByte.setText("Byte");

        bgPergunta2.add(jrbMicrobyte);
        jrbMicrobyte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbMicrobyte.setText("Microbyte");

        bgPergunta2.add(jrbMinibite);
        jrbMinibite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbMinibite.setText("Minibite");

        jlPergunta3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlPergunta3.setText("3: A menor quantidade de informação binaria chama-se:*");

        bgPergunta3.add(jrb1000quilobytes);
        jrb1000quilobytes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrb1000quilobytes.setText("1000 kb (quilobyte)");

        bgPergunta3.add(jrb10Bits);
        jrb10Bits.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrb10Bits.setText("10 bits");

        bgPergunta3.add(jrb1000Megabytes);
        jrb1000Megabytes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrb1000Megabytes.setText("1000 MB (Megabyte)");

        bgPergunta3.add(jrb10000bytes);
        jrb10000bytes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrb10000bytes.setText("10000 bytes");

        jbSubmeter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbSubmeter.setText("Submeter");
        jbSubmeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubmeterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb1000Megabytes)
                            .addComponent(jrb10000bytes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSubmeter, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPergunta1)
                            .addComponent(jlPergunta2)
                            .addComponent(jlPergunta3)
                            .addComponent(jrbMinibite)
                            .addComponent(jrbMicrobyte)
                            .addComponent(jrbByte)
                            .addComponent(jrbBit)
                            .addComponent(jrb1000quilobytes)
                            .addComponent(jrb10Bits))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbSoftware)
                            .addComponent(jrbPerifericos)
                            .addComponent(jrbHardware)
                            .addComponent(jrbModem))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlPergunta1)
                .addGap(21, 21, 21)
                .addComponent(jrbSoftware)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbHardware)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbPerifericos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbModem)
                .addGap(15, 15, 15)
                .addComponent(jlPergunta2)
                .addGap(18, 18, 18)
                .addComponent(jrbBit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbByte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMicrobyte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMinibite)
                .addGap(18, 18, 18)
                .addComponent(jlPergunta3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jrb1000quilobytes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb10Bits)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb1000Megabytes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb10000bytes)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSubmeter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbBitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbBitActionPerformed

    private void jbSubmeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubmeterActionPerformed
        if (!perguntaRespondida(bgPergunta1)) {
            JOptionPane.showMessageDialog(null, "A pergunta 1 não foi respondida");
            return;
        }
        if (!perguntaRespondida(bgPergunta2)) {
            JOptionPane.showMessageDialog(null, "A pergunta 2 não foi respondida");
            return;
        }
        if (!perguntaRespondida(bgPergunta3)) {
            JOptionPane.showMessageDialog(null, "A pergunta 3 não foi respondida");
            return;
        }
        int acertos = 0;
        acertos += jrbHardware.isSelected() ? 1 : 0;
        acertos += jrb1000Megabytes.isSelected() ? 1 : 0;
        acertos += jrbBit.isSelected() ? 1 : 0;
        
        JOptionPane.showMessageDialog(null, "Você acertou "+ acertos+ " resposta(s)!");
    }//GEN-LAST:event_jbSubmeterActionPerformed

    private boolean perguntaRespondida(ButtonGroup pergunta){
        return pergunta.getSelection() != null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPergunta1;
    private javax.swing.ButtonGroup bgPergunta2;
    private javax.swing.ButtonGroup bgPergunta3;
    private javax.swing.JButton jbSubmeter;
    private javax.swing.JLabel jlPergunta1;
    private javax.swing.JLabel jlPergunta2;
    private javax.swing.JLabel jlPergunta3;
    private javax.swing.JRadioButton jrb10000bytes;
    private javax.swing.JRadioButton jrb1000Megabytes;
    private javax.swing.JRadioButton jrb1000quilobytes;
    private javax.swing.JRadioButton jrb10Bits;
    private javax.swing.JRadioButton jrbBit;
    private javax.swing.JRadioButton jrbByte;
    private javax.swing.JRadioButton jrbHardware;
    private javax.swing.JRadioButton jrbMicrobyte;
    private javax.swing.JRadioButton jrbMinibite;
    private javax.swing.JRadioButton jrbModem;
    private javax.swing.JRadioButton jrbPerifericos;
    private javax.swing.JRadioButton jrbSoftware;
    // End of variables declaration//GEN-END:variables
}
