/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pesquia;

import javax.swing.JOptionPane;

/**
 *
 * @author Tech Consertos
 */
public class PesquisaGUI extends javax.swing.JFrame {

    /**
     * Creates new form PesquisaGUI
     */
    public PesquisaGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcboquefaconofind = new javax.swing.JLabel();
        jcbselecione = new javax.swing.JLabel();
        jcbdormindo = new javax.swing.JCheckBox();
        jcbnamorando = new javax.swing.JCheckBox();
        jcbconsertandocelular = new javax.swing.JCheckBox();
        jcbtrabalhando = new javax.swing.JCheckBox();
        jcbdescancando = new javax.swing.JCheckBox();
        jcbtomandoterere = new javax.swing.JCheckBox();
        jcbenviar = new javax.swing.JButton();
        jlTituloSaida = new javax.swing.JLabel();
        jlSaida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O que faço no fim de semana");

        jcboquefaconofind.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jcboquefaconofind.setText("O que mais estou fazendo no fim de semana");

        jcbselecione.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbselecione.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jcbselecione.setText("Você pode escolher mais de uma opção!");

        jcbdormindo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbdormindo.setText("Dormindo");

        jcbnamorando.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbnamorando.setText("Namorando");

        jcbconsertandocelular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbconsertandocelular.setText("Consertando Celular");

        jcbtrabalhando.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbtrabalhando.setText("Trabalhando");

        jcbdescancando.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbdescancando.setText("Descançando");

        jcbtomandoterere.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbtomandoterere.setText("Tomando Tererê");

        jcbenviar.setText("ENVIAR");
        jcbenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbenviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcbselecione, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlTituloSaida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbconsertandocelular)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jcbnamorando, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbdormindo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbdescancando, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbtrabalhando, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbtomandoterere, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jcbenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 258, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcboquefaconofind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSaida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jcboquefaconofind, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbselecione, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jcbdormindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbnamorando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbconsertandocelular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbtrabalhando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbdescancando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbtomandoterere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTituloSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbenviarActionPerformed
        jlSaida.setText("");
        int quantidadeTarefas = 0;
        String tarefasMarcadas = "";
        if (jcbdormindo.isSelected()) {
            quantidadeTarefas++;
            tarefasMarcadas += "Dormindo, ";
        }
        if (jcbnamorando.isSelected()) {
            quantidadeTarefas++;
            tarefasMarcadas += "namorando, ";
        }
        if (jcbnamorando.isSelected()) {
            quantidadeTarefas++;
            tarefasMarcadas += "namorando, ";
        }
        if (jcbconsertandocelular.isSelected()) {
            quantidadeTarefas++;
            tarefasMarcadas += "Consertando Celular, ";
        }
        if (jcbtrabalhando.isSelected()) {
            quantidadeTarefas++;
            tarefasMarcadas += "Trabalhando, ";
        }
        if (jcbdescancando.isSelected()) {
            quantidadeTarefas++;
            tarefasMarcadas += "Descançando, ";
        }
        if (jcbtomandoterere.isSelected()) {
            quantidadeTarefas++;
            tarefasMarcadas += "Tomando Tererê, ";

        }
    if(tarefasMarcadas.equals("")){
     jlTituloSaida.setText( " Allan "
             + "você não escolheu nenhuma tarefa!");
     return;
    }
    jlTituloSaida.setText("   Atividades realizadas por mim!");
    jlSaida.setText(tarefasMarcadas);
    }//GEN-LAST:event_jcbenviarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jcbconsertandocelular;
    private javax.swing.JCheckBox jcbdescancando;
    private javax.swing.JCheckBox jcbdormindo;
    private javax.swing.JButton jcbenviar;
    private javax.swing.JCheckBox jcbnamorando;
    private javax.swing.JLabel jcboquefaconofind;
    private javax.swing.JLabel jcbselecione;
    private javax.swing.JCheckBox jcbtomandoterere;
    private javax.swing.JCheckBox jcbtrabalhando;
    private javax.swing.JLabel jlSaida;
    private javax.swing.JLabel jlTituloSaida;
    // End of variables declaration//GEN-END:variables
}
