/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendaaulas;

/**
 *
 * @author Tech Consertos
 */
public class AgendaGUI extends javax.swing.JFrame {

    /**
     * Creates new form AgendaGUI
     */
    public AgendaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbTitulo = new javax.swing.JLabel();
        jlEnunciado = new javax.swing.JLabel();
        jcbDiaDaSemana = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMaterias = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcbTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbTitulo.setText("AGENDA DE HORÁRIO DAS AULAS");

        jlEnunciado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlEnunciado.setText("Dia da semana:");

        jcbDiaDaSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segunda", "Terça", "Quarta", "Quinta", "Sexta" }));
        jcbDiaDaSemana.setToolTipText("");
        jcbDiaDaSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDiaDaSemanaActionPerformed(evt);
            }
        });

        jtaMaterias.setColumns(20);
        jtaMaterias.setRows(5);
        jScrollPane1.setViewportView(jtaMaterias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 47, Short.MAX_VALUE)
                .addComponent(jlEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jcbDiaDaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jcbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jcbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbDiaDaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbDiaDaSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDiaDaSemanaActionPerformed
        String diaSemana = jcbDiaDaSemana.getSelectedItem().toString();
        switch (diaSemana) {
            case "Segunda":
                jtaMaterias.append("Matemática\n");
                jtaMaterias.append("Matemática\n");
                jtaMaterias.append("Inglês\n");
                jtaMaterias.append("Inglês\n");
                jtaMaterias.append("Geografia\n");
                break;
            case "Terça":
                jtaMaterias.append("Física\n");
                jtaMaterias.append("Educação Física\n");
                jtaMaterias.append("Educação Física\n");
                jtaMaterias.append("Geografia\n");
                jtaMaterias.append("Geografia\n");
                break;
            case "Quarta":
                jtaMaterias.append("Biologia\n");
                jtaMaterias.append("Artes\n");
                jtaMaterias.append("Biologia\n");
                jtaMaterias.append("Espanhol\n");
                jtaMaterias.append("História\n");
                break;
            case "Quinta":
                jtaMaterias.append("Ciências\n");
                jtaMaterias.append("Projeto de Vida\n");
                jtaMaterias.append("Religião\n");
                jtaMaterias.append("Inglês\n");
                jtaMaterias.append("Geografia\n");
                break;
            case "Sexta":
                jtaMaterias.append("Matemática\n");
                jtaMaterias.append("Matemática\n");
                jtaMaterias.append("Inglês\n");
                jtaMaterias.append("Inglês\n");
                jtaMaterias.append("Geografia\n");
                break;

        }
    }//GEN-LAST:event_jcbDiaDaSemanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbDiaDaSemana;
    private javax.swing.JLabel jcbTitulo;
    private javax.swing.JLabel jlEnunciado;
    private javax.swing.JTextArea jtaMaterias;
    // End of variables declaration//GEN-END:variables
}
